language: node_js
cache: 
  directories: 
    - node_modules
    - ~/.npm
node_js: 
  - "14"
script: 
  - "yarn build"
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: 'Deploy Success'
  on:
    branch: master

